// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANjXKbEE4t8UtUKzRGhW_nSzXKmkZaAY0',
    appId: '1:754985842400:web:547ffa8589b199a9d5c285',
    messagingSenderId: '754985842400',
    projectId: 'viprwatch-firebase-project',
    authDomain: 'viprwatch-firebase-project.firebaseapp.com',
    storageBucket: 'viprwatch-firebase-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrMpE0W5pDKjb_I3BOwON_NQAShJN34oY',
    appId: '1:754985842400:android:c4d77a54f1416a1bd5c285',
    messagingSenderId: '754985842400',
    projectId: 'viprwatch-firebase-project',
    storageBucket: 'viprwatch-firebase-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBafQFix91GIJGjk9ds_q5aGsCuoux02MI',
    appId: '1:754985842400:ios:b16221c8e350afe1d5c285',
    messagingSenderId: '754985842400',
    projectId: 'viprwatch-firebase-project',
    storageBucket: 'viprwatch-firebase-project.appspot.com',
    iosBundleId: 'com.example.viprWatchMobileApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBafQFix91GIJGjk9ds_q5aGsCuoux02MI',
    appId: '1:754985842400:ios:ed747a7e3102b107d5c285',
    messagingSenderId: '754985842400',
    projectId: 'viprwatch-firebase-project',
    storageBucket: 'viprwatch-firebase-project.appspot.com',
    iosBundleId: 'com.example.viprWatchMobileApplication.RunnerTests',
  );
}
