// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDzFZj60AVlQ2cGYfxOH7sm-_mwQ9KHJE',
    appId: '1:450752793665:web:23da49acc35cdecdaa4ac0',
    messagingSenderId: '450752793665',
    projectId: 'viprwatch-project',
    authDomain: 'viprwatch-project.firebaseapp.com',
    storageBucket: 'viprwatch-project.appspot.com',
    measurementId: 'G-KCC04QSSFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs11yuQkMllTHDwNms25UOMz6PEFAVXrs',
    appId: '1:450752793665:android:c02c5f70740d94fcaa4ac0',
    messagingSenderId: '450752793665',
    projectId: 'viprwatch-project',
    storageBucket: 'viprwatch-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLDPqKQT-Lz65Si5IrIWzF6e8l55NKyUA',
    appId: '1:450752793665:ios:c76a6265aee04e61aa4ac0',
    messagingSenderId: '450752793665',
    projectId: 'viprwatch-project',
    storageBucket: 'viprwatch-project.appspot.com',
    androidClientId: '450752793665-7nuolk33kv81t9p23doreukmkm34bqqm.apps.googleusercontent.com',
    iosClientId: '450752793665-2lneqousnhcr83q20s1i92upjoe2g3h3.apps.googleusercontent.com',
    iosBundleId: 'com.example.viprWatchMobileApplication',
  );
}
